### ISSUE TITLE
Pickle data files required

### ISSUE THREAD

**Issue by selinacarter** [spotify-research/tdsurv#1]
Hello!

I'm very excited to try this package. However, I can't run the notebooks because they require the data to be in .pkl format. The data/README.txt only explains how to transform them into .csv files via R.

Should we also save the files from a data frame in R to  .pkl file using [this](https://stackoverflow.com/questions/64832745/how-can-i-convert-csv-to-pickle)?

**Comment by lucasmaystre** [comment]
Hi @selinacarter thanks for your interest!

Which notebook are you referring to specifically? For the two datasets, the order in which the notebooks should be read & run is:

1. `*-exploratory-analysis.ipynb` (where * = `pbc2`, `aids`)
2. `*-final.ipynb`
3. `fig-eval.ipynb`

The `.pkl` files will be created in the process.

I agree that this is poorly documented at the moment—I'll try to add some notes on this.

**Comment by selinacarter** [comment]
Fabulous! I think we got it working now. I'll let you know if we have any other buggy issues.

FYI: I'm obsessed with this paper. I was modelling time-to-event stuff before I started my PhD and I couldn't find a model that incorporated prior temporal paths like you have done. You'll be hearing from me again!

**Comment by selinacarter** [comment]
Another issue:

In the following notebooks:
    **fig-eval**
    **fig-datapool**
    
At the line fig.tight_layout(), there are some errors. Somehow the Latex code isn't working (Ref[ this post](https://stackoverflow.com/questions/43295837/latex-was-not-able-to-process-the-following-string-blp)).

Have you ever had this issue?
[error_fig-eval.txt](https://github.com/spotify-research/tdsurv/files/11067546/error_fig-eval.txt)


I am attaching the error output (it's easiest to see in Notepad++ with "Python" language setting).

**Comment by selinacarter** [comment]
FYI, I fixed the last issue. I had to comment out the line `setup_plotting()` (from tdsurv.plotting) to get the figures to print. I think the issue is the `"text.usetex": True` parameter. There's something sinister going on according to [this post](https://stackoverflow.com/questions/43295837/latex-was-not-able-to-process-the-following-string-blp).

**Comment by lucasmaystre** [comment]
Sorry for the belated reply—you are right, commenting out the call to `setup_plotting` is the easiest way to fix it.

For the paper, I decided to typeset text in the plots with latex, but unfortunately the matplotlib / latex interface is very brittle, as you've discovered...
